### ISSUE TITLE
rye install does not fetch

### ISSUE THREAD

**Issue by douardda** [mitsuhiko/rye#17]
I just installed rye on a Debian bullseye and tested a simple install:

```
$ rye install platformio
Bootstrapping rye internals
Downloading cpython@3.10.9
success: Downloaded cpython@3.10.9
Upgrading pip
Installing internal dependencies
FileNotFoundError: [Errno 2] No such file or directory: '/home/ddouard/.rye/py/cpython@3.11.1/install/bin/python3'
error: failed to initialize virtualenv
```

notice the mixup between py 3.11 and py 3.10 here.

PS: Installed rye v0.1.0 (https://github.com/mitsuhiko/rye#eaf12925) using rust 1.67.0 (fc594f156 2023-01-24)
Note that I did not run any other command between the `cargo install rye` and the command above.
After a `rye fetch 3.11`, the `rye install` command does work, but any `rye sync` or `rye run` command complains about the lack of a `pyproject.toml` file (which I don't expect to be necessary to install a python package 'globally').

Thanks!

**Comment by mitsuhiko** [comment]
The `pyproject.toml` file is mandatory, but the error reporting capabilities of rye are … lacking.

The issue here might be that rye fails to auto install missing Python versions when it uses `install`. It always uses `3.10` internally because that's the version of Python I used it with originally, but it picks the latest available Python for `install`.
