### ISSUE TITLE
`~/.rye/shims/python` acts like it's `rye`

### ISSUE THREAD

**Issue by loqusion** [mitsuhiko/rye#439]
### Steps to Reproduce

1. Install rye binary (e.g. via package manager, I used pacman)
2. Make sure `~/.rye` directory has not been created (pacman doesn't create it upon installation, for example)
3. `rye init foo; cd foo; rye sync`
4. `~/.rye/shims/python` acts like `rye`, even after installing rye to `~/.rye/` and running `rye sync` again

### Expected Result

There are a couple of ways to go about this, but generally speaking the `python` in `~/.rye/shims/` should probably act like a valid python executable whenever it exists, or else having it in your `$PATH` can silently break other applications (e.g. system updates with `PKGBUILD`s).

### Actual Result

![image](https://github.com/mitsuhiko/rye/assets/38332081/d93c15ce-ddd6-41af-9b13-e43f4cbb1ad7)

### Version Info

```
rye 0.14.0
commit: 0.13.0+5 (265a0e020 2023-08-31)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by mitsuhiko** [comment]
I do not use pacman so it's hard for me to debug this, but I'm not entirely sure how it's possible for this to happen. It sounds like the shim detection code is broken here.

Can you run this for me?

```
ls -alh ~/.rye/shims
```

I suppose what is happening is that `detect_shim` returns `None`:

https://github.com/mitsuhiko/rye/blob/265a0e020c1554c67ad7c715f49965cf69296547/rye/src/cli/shim.rs#L21

**Comment by loqusion** [comment]
After running `rye sync`:

```
total 8.0K
drwxr-xr-x 1 loqusion loqusion 26 Sep  5 18:00 .
drwxr-xr-x 1 loqusion loqusion 40 Sep  5 18:00 ..
lrwxrwxrwx 1 loqusion loqusion 12 Sep  5 18:00 python -> /usr/bin/rye
lrwxrwxrwx 1 loqusion loqusion 12 Sep  5 18:00 python3 -> /usr/bin/rye
```

After installing rye via `rye`/`python`:

```
total 15M
drwxr-xr-x 1 loqusion loqusion  32 Sep  5 18:02 .
drwxr-xr-x 1 loqusion loqusion  46 Sep  5 18:02 ..
lrwxrwxrwx 1 loqusion loqusion  12 Sep  5 18:02 python -> /usr/bin/rye
lrwxrwxrwx 1 loqusion loqusion  12 Sep  5 18:02 python3 -> /usr/bin/rye
-rwxr-xr-x 1 loqusion loqusion 15M Sep  5 18:02 rye
```

**Comment by mitsuhiko** [comment]
I think I know what is happening here. We have code that avoids the use of symlinks on Linux:

https://github.com/mitsuhiko/rye/blob/265a0e020c1554c67ad7c715f49965cf69296547/rye/src/bootstrap.rs#L208-L212

It however falls back to symlinks when hardlinks fail. That's pretty dumb because honestly, a symlink will not work on Linux. The issue here is basically that `rye` on your machine is placed in `/usr/bin/rye` and i assume your home folder is on a different volume. Then the fallback logic kicks in which is a symlink and that fails, because symlinks misreport on Linux. The fallback in this case really needs to be changed to a copy.

**Comment by Xinkai** [comment]
I found this issue because I was surprised that `~/.rye/shims/python` is not symlinked to `/usr/bin/rye` but a copy.

As stated in the [current_exe doc](https://doc.rust-lang.org/1.78.0/std/env/fn.current_exe.html#platform-specific-behavior), it is not a reliable way to detect whether the current process is started via a symlink. Linux-specifically, `current_exe` reads `/proc/self/exe`. It returns the executable image being loaded to the memory.

We want to use `env::args()[0]` or `env::args_os()[0]` to detect how the current invocation was done.

```rust
use std::env;

fn main() {
    for arg in env::args() {
        println!("args: {:?}", &arg);
    }

    for arg in env::args_os() {
        println!("args_os: {:?}", &arg);
    }

    println!("current_exe: {:?}", env::current_exe());
}
```

```text
# Invoke via the binary name
$ ./symlink_invoke
args: "./symlink_invoke"
args_os: "./symlink_invoke"
current_exe: Ok("/home/xinkai/projects/Rust/symlink_invoke/target/x86_64-unknown-linux-musl/debug/symlink_invoke")

$ ln -sf ./symlink_invoke ./via_sym
$ ./via_sym
args: "./via_sym"
args_os: "./via_sym"
current_exe: Ok("/home/xinkai/projects/Rust/symlink_invoke/target/debug/symlink_invoke")
```
