### ISSUE TITLE
Suggestion: Add an ability to swap `default global` version in the toolchain

### ISSUE THREAD

**Issue by Amoenus** [mitsuhiko/rye#455]
Consider adding a feature that allows users to pick and use a specific version of Python from the toolchain as a global default

something like:
`rye toolchain use cpython@3.11.5`

**Comment by mitsuhiko** [comment]
A global default in which way? For a python picked up outside of a virtualenv or as a default when creating new projects?

**Comment by mitsuhiko** [comment]
It picks up the `default.toolchain`.

```
mitsuhiko at cheetah in ~ exited 1
$ rye config --set default.toolchain=3.11

mitsuhiko at cheetah in ~
$ python
Python 3.11.6 (main, Oct  2 2023, 20:31:07) [Clang 16.0.3 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D

mitsuhiko at cheetah in ~
$ rye config --set default.toolchain=3.12

mitsuhiko at cheetah in ~
$ python
Python 3.12.0 (main, Oct  2 2023, 20:56:14) [Clang 16.0.3 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by Amoenus** [comment]
Interesting. It doesn't work for me at all

```Shell
rye config --set default.toolchain=3.11.5
python --version
Python 3.11.4

rye config --set default.toolchain=3.8.5
python --version
Python 3.11.4

rye config --set default.toolchain=cpython@3.11.5
python --version
Python 3.11.4
```
![image](https://github.com/mitsuhiko/rye/assets/5391396/26feb709-c41d-490f-a8a6-104cce2696cd)


system info:
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621

PowerShell 7.3.7

**Comment by unique1o1** [comment]
Yeah, did that by changing the config file itself too, but it doesn't seem to work.

**Comment by Amoenus** [comment]
Also for sanity check python points to rye shim:

```shell
Get-Command python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         0.0.0.0    C:\Users\RomansPokrovskis\.rye\shims\python.exe
```

**Comment by mitsuhiko** [comment]
It sounds to me that the shim is not being used. Potentially a different Python overshadows it.

**Comment by unique1o1** [comment]
![image](https://github.com/mitsuhiko/rye/assets/15344081/31aaba85-59e3-4773-b68d-dc83a862f0a4)

It is pointing to the shim and using the full path to the shim results in the same outcome as well.

System info:
OS Name: Pop!_OS
OS Version:  22.04 LTS

**Comment by Minkiu** [comment]
Hey, 

thanks for Rye, I've recently started trying it;

I'm experiencing the same on Fedora 38; I checked and the `~/.rye/shims/python` is a binary, where is the code that compiles to that binary in the project? Or is the actual `python` binary (from the downloaded install)?

I am new to rust, but tried to do some digging;

If its the actual binary, this lines in [`installer.rs`](https://github.com/mitsuhiko/rye/blob/main/rye/src/installer.rs#L270-L273) struck me as "odd" since they don't do the whole symlinks check that [`bootstrap.rs`](https://github.com/mitsuhiko/rye/blob/main/rye/src/bootstrap.rs#L214-L222) does:

If it's in `shim.rs` as far as I understand, it defers to the [`get_python_version_request_from_pyenv_pin`](https://github.com/mitsuhiko/rye/blob/main/rye/src/cli/shim.rs#L146C10-L150)

Which in turn looks for a `.python-version` in the  `&std::env::current_exe()`  I don't know what that resolves to, but I couldn't find any such file in the `~/.rye` folder (assuming that's where it's looking), I tried adding on in all the folders with the contents `cpython-x86_64-linux@3.12.0` but `rye` kept defaulting to the system python. Also tried in the shell's `pwd`, without much luck.

I would assume that if `if config.global_python()` evaluates to something truthy we run the found version, from the `~/.rye/py` folder?

```bash
$ rye config --get default.toolchain
3.12

$ rye toolchain list
cpython@3.12.0 (/home/minkiu/.rye/py/cpython@3.12.0/install/bin/python3)
cpython@3.11.6 (/home/minkiu/.rye/py/cpython@3.11.6/install/bin/python3)
```

Hope that helps!
Cheers.

**Comment by mhrjimmy** [comment]
I have the exact same problem too.

```
$ rye config --get default.toolchain
3.12

$ which python
/home/jim/.rye/shims/python
```

but executing python gets the 3.10 REPL

**Comment by unique1o1** [comment]
It turns out you have to opt-in to have rye resolve to a rye-managed Python installation. 

`$ rye config --set-bool behavior.global-python=true` 

It is documented [here](https://rye-up.com/guide/shims/).

**Comment by Amoenus** [comment]
I believe I already had that flag, but double checked anyway:

No change, sadly
<img width="1709" alt="image" src="https://github.com/mitsuhiko/rye/assets/5391396/298225c8-558b-425b-94ce-c10f137a4016">

**Comment by Amoenus** [comment]
I also noticed `requires-python = ">= 3.11"` in rye's config.toml but manipulating version in any way (or deleting the line) doesn't seem to do anything

**Comment by mitsuhiko** [comment]
Rye only picks up on it's own python versions if one of those two things are true:

1. you are in a python project (`pyproject.toml`)
2. you have global python shims enabled (`rye config --set-bool behavior.global-python=true`)

Is the latter not working for you or is it insufficient?

**Comment by mitsuhiko** [comment]
I'm closing this as resolved for now. If the current behavior (picking up `.python-version`) is not sufficient please let me know.
