### ISSUE TITLE
`behavior.global-python` does not use `.python-version` ?$ 

### ISSUE THREAD

**Issue by ras0q** [mitsuhiko/rye#481]
### Steps to Reproduce

```sh
$ rye config --set-bool behavior.global-python=true
$ rye toolchain fetch 3.11 #optional
$ rye toolchain fetch 3.12 # optional
$ rye pin 3.11
$ python3 --version # will get 3.12
```

### Expected Result

same as a pinned version (in `.python-version` file)

### Actual Result

![image](https://github.com/mitsuhiko/rye/assets/66677201/9a1689d9-fe9c-4ee7-b4c6-f63b8084710a)

### Version Info

This reproduces in Windows11 PowerShell and WSL2

```sh
$ rye --version
rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true
```

```sh
$ rye --version
rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by rmarquis** [comment]
This only works if a `pyproject.toml` file is detected.

I don't know if this is by design, but I'm often in the situation where I have to work with legacy projects (which use the old requirements.txt file) that don't use a `pyproject.toml` file, and I can't really use rye to manage and switch the required python versions due to this issue.

As a cheap, quick and dirty workaround, I'm generating a dummy pyproject.toml file with `rye init`, after removing this file when my work is done.

**Comment by rmarquis** [comment]
@mitsuhiko Is the above the expected behaviour? Asking because I'd be interested in making it "just work" and dive into the code to prepare a PR (I'm new to Rust though).

**Comment by mitsuhiko** [comment]
I think it makes sense to change it so that `.python-version` is honored no matter what.
