### ISSUE TITLE
Failed to work with `mypy --install-types .`

### ISSUE THREAD

**Issue by liebkne** [mitsuhiko/rye#513]
### Steps to Reproduce

1. Install `mypy` by `rye install mypy`.
2. Run `mypy` on some project with command `mypy --install-types .`.

### Expected Result

Missing stub packages are installed.

### Actual Result

```
Installing missing stub packages:
/Users/user/.rye/tools/mypy/bin/python -m pip install types-python-dateutil types-requests

Install? [yN] y

/Users/user/.rye/tools/mypy/bin/python: No module named pip

note: Run mypy again for up-to-date results with installed types
```

### Version Info

```
rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: macos (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by liebkne** [comment]
Hi, I'm not sure if I understand correctly. `--extra-requirement` seems to be options of tools. But shouldn't stub packages are install for individual virtualenvs of different Python version?

**Comment by ischaojie** [comment]
If you want to use it in the project's own virtual environment, you should be able to use it via `rye add types-python-dateutil types-requests & rye sync` (not verified)?

**Comment by mitsuhiko** [comment]
This error happens because `pip` is not installed into virtualenvs managed by rye. This is very intentional but it does have this unfortunate effect. You can install pip into that virtualenv by adding it as a requirement, but manually managed tools and dependencies will likely be removed on next sync.

It's better to directly add requirements instead of relying on other tools installing stuff.
